---
- name: "Install Prerequisites."
  ansible.builtin.package:
    name: openjdk-11-jdk,screen
    state: present

- name: "Check Minecraft Save Status."
  become: 'false'
  ansible.builtin.stat:
    path: files/minecraft.zip
  register: minecraft_save_status
  delegate_to: localhost
  when: minecraft_use_archive | bool

- name: "Upload Save."
  ansible.builtin.copy:
    src: minecraft.zip
    dest: /tmp/minecraft.zip
  when: (minecraft_use_archive | bool) and (minecraft_save_status.stat.exists | bool)

- name: "Unpack Save."
  ansible.builtin.unarchive:
    src: /tmp/minecraft.zip
    dest: /opt/
    keep_newer: 'yes'
    remote_src: 'yes'
  when: (minecraft_use_archive | bool) and (minecraft_save_status.stat.exists | bool)

- name: Configure SSH.
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/root/.ssh/{{ item }}"
    owner: root
    group: root
    mode: 0600
  with_items:
    - minecraft-git-key
    - config
  when: (minecraft_use_git | bool)

- name: Checkout Server from github.
  ansible.builtin.git:
    repo: "{{ minecraft_git_repo }}"
    dest: "{{ minecraft_root }}"
    key_file: /root/.ssh/minecraft-git-key
    accept_hostkey: yes
  when: (minecraft_use_git | bool)

- name: "Ensure Server Directory exists."
  ansible.builtin.file:
    path: "{{ minecraft_root }}"
    state: directory

- name: "Get Minecraft Server."
  ansible.builtin.get_url:
    url: "{{ minecraft_server_jar_download }}"
    dest: "{{ minecraft_root }}/server.jar"
    owner: root
    group: root
    mode: 0750

- name: "Copy Minecraft Configuration."
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ minecraft_root }}/{{ item }}"
    owner: root
    group: root
    mode: 0700
  with_items:
    # - server.properties
    - whitelist.json
    - ops.json

- name: "Copy Minecraft Files."
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ minecraft_root }}/{{ item }}"
    owner: root
    group: root
    mode: 0700
  with_items:
    - git_config.sh
    - git_commit.sh
    - run_server.sh
    - server.properties
    - eula.txt

- name: "Configure Git."
  ansible.builtin.shell: "bash {{ minecraft_root }}/git_config.sh"
  when: (minecraft_use_git | bool)

- name: "Run Server in Screen."
  ansible.builtin.shell: "screen -S minecraft -d -m bash -c {{ minecraft_root }}/run_server.sh && sleep 1"
